FROM binomio/mongo

WORKDIR /data/db

RUN echo "Dockerfile"

# ARG MONGO_DB_ADMIN_USER
# ARG MONGO_DB_ADMIN_PASSWORD
# ARG DB
# ARG MONGO_USERNAME

# RUN echo $MONGO_USERNAME
# RUN echo "MONGO_DB_ADMIN_PASSWORD:${MONGO_DB_ADMIN_PASSWORD}"

# COPY ./config/mongo/mongo.js /docker-entrypoint-initdb.d/init-mongo.js

CMD ["mongo"]
